<?php
/**
 * UploadsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  amznSellingPartnerApiPhpSdk\Uploads_2020-11-01
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Uploads
 *
 * The Selling Partner API for Uploads provides operations that support uploading files.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace amznSellingPartnerApiPhpSdk\Uploads_2020-11-01;

use amznSellingPartnerApiPhpSdk\Uploads_2020-11-01\Configuration;
use amznSellingPartnerApiPhpSdk\Uploads_2020-11-01\ApiException;
use amznSellingPartnerApiPhpSdk\Uploads_2020-11-01\ObjectSerializer;

/**
 * UploadsApiTest Class Doc Comment
 *
 * @category Class
 * @package  amznSellingPartnerApiPhpSdk\Uploads_2020-11-01
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UploadsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createUploadDestinationForResource
     *
     * .
     *
     */
    public function testCreateUploadDestinationForResource()
    {
    }
}
